# Generated by Django 4.2.3 on 2023-07-11 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='aucun', max_length=50, null=True)),
                ('prenom', models.CharField(default='aucun', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='aucun', max_length=100, null=True)),
                ('budget', models.CharField(default='aucun', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='aucun', max_length=50, null=True)),
                ('etage', models.CharField(default='aucun', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransfertMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_transfert', models.DateField()),
                ('lieu_transfer', models.CharField(max_length=100)),
                ('occasion', models.CharField(max_length=100)),
                ('objectif', models.TextField()),
                ('ancien_possesseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferts_sortants', to='gestion_materiel.enseignant')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_materiel.materiel')),
                ('nouveau_possesseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferts_entrants', to='gestion_materiel.enseignant')),
            ],
        ),
        migrations.AddField(
            model_name='materiel',
            name='lieu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_materiel.salle'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='possesseur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiels_en_possession', to='gestion_materiel.enseignant'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='proprietaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiels_possedes', to='gestion_materiel.enseignant'),
        ),
        migrations.CreateModel(
            name='AccessoireMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('present', models.BooleanField(default=True)),
                ('etat', models.CharField(max_length=100)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_materiel.materiel')),
            ],
        ),
    ]
